language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
services:
  - mongodb
install:
  - pip install -e .[test]
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' || $TRAVIS_PYTHON_VERSION == 'nightly' ]]; then pip install -e .[experimental_aio]; fi
script:
  - nosetests --exclude-test=test.test_lsh_mongo
  - export DO_TEST_MONGO=true
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' || $TRAVIS_PYTHON_VERSION == 'nightly' ]]; then nosetests test.test_lsh_mongo; fi
